language: minimal

sudo: required
services:
  - docker

before_install:
  - docker build -t vsuzdaltsev/react-test -f ./client/Dockerfile.dev ./client
#  - docker run vsuzdaltsev/react-test npm test -- --coverage

after_success:
  - docker build -t vsuzdaltsev/multi-client ./client
  - docker build -t vsuzdaltsev/multi-nginx ./nginx
  - docker build -t vsuzdaltsev/multi-server ./server
  - docker build -t vsuzdaltsev/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker Login -u "$DOCKER_ID" --password-stdin
  - docker push vsuzdaltsev/multi-client
  - docker push vsuzdaltsev/multi-nginx
  - docker push vsuzdaltsev/multi-server
  - docker push vsuzdaltsev/multi-worker
